In [2]:
import pandas as pd

fake = pd.read_csv("../data/raw/Fake.csv")
true = pd.read_csv("../data/raw/True.csv")

print("Fake news:", fake.shape)
print("Real news:", true.shape)

Fake news: (23481, 4)
Real news: (21417, 4)

In [3]:
print("Fake dataset columns:")
print(fake.columns.tolist())

print("\nReal dataset columns:")
print(true.columns.tolist())

Fake dataset columns:
['title', 'text', 'subject', 'date']

Real dataset columns:
['title', 'text', 'subject', 'date']

In [4]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
print("Fake dataset missing values:")
print(fake.isnull().sum())

print("\nReal dataset missing values:")
print(true.isnull().sum())

Fake dataset missing values:
title      0
text       0
subject    0
date       0
dtype: int64

Real dataset missing values:
title      0
text       0
subject    0
date       0
dtype: int64

In [7]:
fake["label"] = 0
true["label"] = 1

df = pd.concat([fake, true], ignore_index=True)

print("Total articles:", len(df))
print("\nLabel counts:")
print(df["label"].value_counts())

Total articles: 44898

Label counts:
label
0    23481
1    21417
Name: count, dtype: int64

In [8]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(df.head())

                                               title  \
0  Ben Stein Calls Out 9th Circuit Court: Committ...
1  Trump drops Steve Bannon from National Securit...
2  Puerto Rico expects U.S. to lift Jones Act shi...
3   OOPS: Trump Just Accidentally Confirmed He Le...
4  Donald Trump heads for Scotland to reopen a go...

                                                text       subject  \
0  21st Century Wire says Ben Stein, reputable pr...       US_News
1  WASHINGTON (Reuters) - U.S. President Donald T...  politicsNews
2  (Reuters) - Puerto Rico Governor Ricardo Rosse...  politicsNews
3  On Monday, Donald Trump once again embarrassed...          News
4  GLASGOW, Scotland (Reuters) - Most U.S. presid...  politicsNews

                  date  label
0    February 13, 2017      0
1       April 5, 2017       1
2  September 27, 2017       1
3         May 22, 2017      0
4       June 24, 2016       1

In [9]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 209

In [10]:
df = df.drop_duplicates().reset_index(drop=True)

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 44689

In [11]:
df.to_csv("../data/processed/cleaned_news.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [12]:
print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nLabel distribution:")
print(df["label"].value_counts())

print("\nSample article:")
print(df[["title", "text", "label"]].head(2))

Dataset shape: (44689, 5)

Columns:
['title', 'text', 'subject', 'date', 'label']

Label distribution:
label
0    23478
1    21211
Name: count, dtype: int64

Sample article:
                                               title  \
0  Ben Stein Calls Out 9th Circuit Court: Committ...
1  Trump drops Steve Bannon from National Securit...

                                                text  label
0  21st Century Wire says Ben Stein, reputable pr...      0
1  WASHINGTON (Reuters) - U.S. President Donald T...      1